services:
  brainbay.rickandmorty.webapp:
    image: brainbay.rickandmorty.webapp
    build:
      context: .
      dockerfile: src/Brainbay.RickAndMorty.WebApp/Dockerfile

  brainbay.rickandmorty.consoleapp:
    image: brainbay.rickandmorty.consoleapp
    build:
      context: .
      dockerfile: src/Brainbay.RickAndMorty.ConsoleApp/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
  mysqlserver:
    image: mysql:8.2.0
    container_name: 'my_sql_server_8_2_0_1'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
    volumes:
      - my-db:/var/lib/mysql
  
volumes:
  my-db:
  sqlserverdata: